{% set name = "pymeep" %}
{% set version = "1.15.1.dev" %}
{% set buildnumber = 24 %}
# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set buildnumber = buildnumber + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/NanoComp/meep.git
  git_rev: master

build:
  number: {{ buildnumber }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pymeep * mpi_mpich_*` for mpich
  # `pymeep * mpi_*` for any mpi
  # `pymeep * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_py{{ py }}_nomklh{{ PKG_HASH }}_{{ buildnumber }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  features:
    - nomkl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - guile
    - swig
    - autoconf
    - automake
    - m4
    - libtool
    - pkg-config
    - make


  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - libctl
    - harminv
    - mpb * {{ mpi_prefix }}_*
    - gsl
    - hdf5 * {{ mpi_prefix }}_*
    #- openblas
    - numpy 1.16
    - libgdsii
    - mpi4py  # [mpi != 'nompi']

  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - libctl
    - harminv
    - mpb * {{ mpi_prefix }}_*
    - {{ pin_compatible('numpy') }}
    #- openblas
    - hdf5 * {{ mpi_prefix }}_*
    - gsl
    #- h5utils * {{ mpi_prefix }}_*
    - h5py * {{ mpi_prefix }}_*
    - scipy
    - matplotlib-base >=2.2
    - libgdsii
    - mpi4py  # [mpi != 'nompi']
    - ffmpeg
    - mayavi
    - autograd

test:
  requires:
    - parallel
  imports:
    - meep
  source_files:
    - tests/cyl-ellipsoid-eps-ref.h5
    - python/tests/*.py
    - python/tests/data/*

about:
  home: https:/github.com/NanoComp/meep
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Free finite-difference time-domain (FDTD) software for electromagnetic simulations
  doc_url: https://meep.readthedocs.io
  dev_url: https://github.com/NanoComp/meep
